=== NadineHafner/MUL-SS-2021-Hafner/blatt02/01-kursprogramm.dtd
<!ELEMENT kursprogramm (kurs+)>
<!ELEMENT kurs (bezeichnung,kursinhalt,referententeam,termin,anhang,nachfolgekurs?)>
<!ELEMENT bezeichnung (#PCDATA)>
<!ELEMENT kursinhalt (#PCDATA)>
<!ELEMENT termin (#PCDATA)>
<!ELEMENT anhang (#PCDATA)>
<!ELEMENT nachfolgekurs (#PCDATA)>
<!ELEMENT referententeam (referent+)>
<!ELEMENT referent (name,adresse,kontakt,bild?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT adresse (#PCDATA)>
<!ELEMENT kontakt (tel*,email*)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST kursinhalt lang CDATA #IMPLIED>
<!ATTLIST kurs k_id ID #REQUIRED>
<!ATTLIST nachfolgekurs k_id IDREF #REQUIRED>
<!ATTLIST referent ref_id ID #REQUIRED>
<!ELEMENT bild (ANY*)>

=== NadineHafner/MUL-SS-2021-Hafner/blatt02/practicals_02-sourcecode_01-kursprogramm.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kursprogramm SYSTEM "01-kursprogramm.dtd">
<kursprogramm> 
  <kurs k_id="xml1">
    <bezeichnung>XML Intro</bezeichnung>
    <kursinhalt lang="de">Praxiskurz XML</kursinhalt>
    <referententeam>
      <referent ref_id="_01">
        <name>Max Mustermann</name>
        <adresse>Hauptplatz 2, 8010 Graz</adresse>
        <kontakt>
          <tel>0316 123898</tel>
          <email>max@mustermann.at</email>
        </kontakt>
        <bild />
      </referent>
    </referententeam>
    <termin>05.04.2021</termin>
    <anhang>Der Kurs findet alle 3 Wochen erneut statt.</anhang>
    <nachfolgekurs k_id="xml2" />
  </kurs>

  <kurs k_id="xml2">
    <bezeichnung>XML Intro</bezeichnung>
    <kursinhalt>Praxiskurz XML</kursinhalt>
    <referententeam>
      <referent ref_id="_02">
        <name>Martina Mustermann</name>
        <adresse>Hauptplatz 4, 8010 Graz</adresse>
        <kontakt>
          <email>martina@mustermann.at</email>
        </kontakt>
      </referent>
    </referententeam>
    <termin>05.04.2021</termin>
    <anhang>Der Kurs findet alle 3 Wochen erneut statt.</anhang>
  </kurs>   
</kursprogramm>
